sudo: false

language: c

env:
  - PATH=$HOME/.nimble/bin:$PATH

cache:
  directories:
    - $HOME/.nimble
    - $HOME/.choosenim

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libsdl1.2-dev
      - libgc-dev
      - libsfml-dev

before_install:
  - if [ ! -e $HOME/.nimble/bin/nim ]; then curl https://nim-lang.org/choosenim/init.sh -sSf -o init.sh && bash init.sh -y; choosenim update stable; fi

script:
  - nimble ci

deploy:
  - provider: pages
    skip-cleanup: true
    github-token:
      secure: EqAA8Ul/G+4L5Q0Pa95axbwZOCtjqSzV2/K6pnDIPaE4umy6T46v61Kyjhk4tU2Z67IjJoRfNC85+IRGAT77x4cvsX0p1HOYW0Ax67aBSA31zd553TU83iGt+4wJXOp4iYEzyiJBXoQgajgZuTEbyd6Xwl6Xz6iJnPYU6lqLqDC0Iun3p9riZ3vzHnmnjahIE7VYW5af14opD92rgDMyLkZAXyN2CTmSvFTob+rnJLSTOkAKL93e7RFNhh5bPIwUifZvJWnfMSe9DVvZOtWef0pwlARMcLlPSDym9Y+P/t2+tsYgjwgXNWSmVpSzx991LCTOu2TMSy94XMc4uX5OigxXeYnNQ/i74A5WLwHgITXzw9lld5V6KGfCIXFdYv6X+tdCWqlPjsIKvG5nDZPneb4o4FzgQzONf54MlQT1C75l3OGpY/VFuYRvfaLtJvEvSp43TgqAfLO7kTzknBU4wsqDU2mPFyQOX6G0Z3xx0eYqGfzUzw5bddPdSJEoZ3b5aD2q5owKebtwncCq6QW9eZaotDy5R6nWX1hQujLUgMwkxrq9AAJcscQrvPeldQLTy0oM2oMtj7+P/mEzy6dmIbSFkYg61lPSTBThGagW2J1UqoOEBY1bfKOvvL/XWY/EJBm5TYy18e6GNlRensTEJAxD5dEX0Jsu2MmGJ4WWR78=
    keep-history: true
    local-dir: docs
    target-branch: gh-pages
    on:
      branch: master
